#!/usr/bin/env python3
"""Scanner for the devin-superset-automation pipeline.

Scans a local Superset checkout for remediation candidates:
  - `: any` TypeScript annotations per directory
  - direct `antd` imports (violates @superset-ui/core/components standard)
  - eslint-disable suppressions by rule
  - `npm audit` criticals (optional, when npm is available)

Outputs findings.json + prints a summary. With --create-issues it upserts a
GitHub issue per finding that crosses its threshold, tagged for dispatch.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.request
from collections import Counter
from pathlib import Path

FE = "superset-frontend/src"

ANY_RE = re.compile(r":\s*any\b")
ANTD_RE = re.compile(r"""from ['"]antd['"]""")
ESLINT_RE = re.compile(r"eslint-disable(?:-next-line)?[ \t]+([^\n*]+)")
RULE_NAME_RE = re.compile(r"^[a-zA-Z@][a-zA-Z0-9/@_-]*$")


def iter_source(root: Path):
    for ext in ("*.ts", "*.tsx"):
        yield from root.rglob(ext)


def scan(repo: Path) -> dict:
    src = repo / FE
    any_counts: Counter = Counter()
    antd_files: list[str] = []
    eslint_rules: Counter = Counter()
    total_any = 0

    for f in iter_source(src):
        rel = str(f.relative_to(repo))
        try:
            text = f.read_text(errors="replace")
        except OSError:
            continue
        n_any = len(ANY_RE.findall(text))
        if n_any:
            parent = f.relative_to(src).parent
            parts = parent.parts[:2]
            top = "/".join(parts) if parts else "(root)"
            any_counts[top] += n_any
            total_any += n_any
        if ANTD_RE.search(text):
            antd_files.append(rel)
        for m in ESLINT_RE.findall(text):
            for r in m.split(","):
                r = r.strip().split(" --")[0].strip().rstrip("*/ ").strip()
                if RULE_NAME_RE.match(r):
                    eslint_rules[r] += 1

    npm_audit = None
    try:
        out = subprocess.run(
            ["npm", "audit", "--json", "--omit=dev"],
            cwd=repo / "superset-frontend",
            capture_output=True, text=True, timeout=180,
        )
        if out.stdout:
            data = json.loads(out.stdout)
            npm_audit = data.get("metadata", {}).get("vulnerabilities", {})
    except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError):
        pass

    return {
        "total_any": total_any,
        "any_by_dir": dict(any_counts.most_common()),
        "antd_files": antd_files,
        "eslint_disable_by_rule": dict(eslint_rules.most_common()),
        "npm_audit": npm_audit,
    }


FINDING_RULES = [
    {
        "id": "any-hotspots",
        "title": "chore(frontend): `any` type hotspots — {dir} ({count} occurrences)",
        "labels": ["type-safety", "frontend", "code-quality"],
        "min_count": 8,
        "limit": 3,
    },
]


def gh(method: str, token: str, repo: str, path: str, body=None):
    r = urllib.request.Request(
        f"https://api.github.com/repos/{repo}{path}",
        method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        data=json.dumps(body).encode() if body is not None else None,
    )
    with urllib.request.urlopen(r) as resp:
        return json.loads(resp.read() or b"{}")


def upsert_issues(findings: dict, repo: str, token: str, dispatch_label: str):
    existing = gh("GET", token, repo, "/issues?state=open&per_page=100")
    titles = {i["title"] for i in existing}
    created = []

    rule = FINDING_RULES[0]
    dirs = [(d, c) for d, c in findings["any_by_dir"].items() if c >= rule["min_count"]]
    for d, c in dirs[: rule["limit"]]:
        title = rule["title"].format(dir=d, count=c)
        if title in titles:
            continue
        body = (
            f"## Context\nAuto-generated by the devin-superset-automation scanner.\n\n"
            f"`superset-frontend/src/{d}` contains **{c} `: any` annotations** "
            f"(repo standard: no `any` types).\n\n## Acceptance criteria\n"
            f"- [ ] Zero `: any` annotations remain in `superset-frontend/src/{d}`\n"
            f"- [ ] `npx tsc --noEmit` passes in `superset-frontend`\n"
        )
        issue = gh("POST", token, repo, "/issues",
                   {"title": title, "body": body, "labels": rule["labels"] + [dispatch_label]})
        created.append(issue["html_url"])
    return created


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--repo", default=".", help="path to superset checkout")
    p.add_argument("--out", default="findings.json")
    p.add_argument("--create-issues", action="store_true")
    p.add_argument("--target-repo", default=os.environ.get("TARGET_REPO", "HirenRMistry/superset"))
    p.add_argument("--dispatch-label", default=os.environ.get("DISPATCH_LABEL", "devin-fix"))
    args = p.parse_args()

    findings = scan(Path(args.repo))
    Path(args.out).write_text(json.dumps(findings, indent=2))
    print(json.dumps({k: v for k, v in findings.items() if k != "eslint_disable_by_rule"}, indent=2)[:4000])
    print(f"\ntop eslint-disable rules: {dict(list(findings['eslint_disable_by_rule'].items())[:8])}")
    print(f"findings written to {args.out}")

    if args.create_issues:
        token = os.environ.get("GH_TOKEN")
        if not token:
            sys.exit("GH_TOKEN required for --create-issues")
        created = upsert_issues(findings, args.target_repo, token, args.dispatch_label)
        print(f"created {len(created)} issues: {created}")


if __name__ == "__main__":
    main()
